# Generated by Django 4.1.2 on 2024-06-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=6)),
                ('comentario', models.CharField(max_length=300)),
                ('editorial', models.CharField(max_length=15)),
                ('imagen', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('paginas', models.IntegerField(max_length=3)),
                ('tamaño', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField(max_length=2)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='comics.categoria')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
