# Generated by Django 4.1.2 on 2024-06-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comic',
            name='paginas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comic',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
