# Generated by Django 4.1.2 on 2024-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_comic_cantidad_alter_comic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comentario',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comic',
            name='imagen',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='comic',
            name='tamaño',
            field=models.CharField(max_length=25),
        ),
    ]
